Pipeline test
cnvrg/data-connectors pull request #21
Opened 2022-11-10 21:54 UTC by madhuintel

2022-11-21 20:13 UTC, jedwards-habana requested changes
I think the pipeline files should have a common naming format. Something like pr-monday-connector.yaml. I think we can drop the unit testtest on the end. Also, lets use '-' instead of underscores.

2022-11-21 20:15 UTC, jedwards-habana requested changes

2022-11-21 20:15 UTC, jedwards-habana commented on .github/workflows/monday_connector_unittests.yaml
> +  build:
This isn't a build step. It is a 'unittest' step. This text will show as 'build' in the step automation and it should be consistent with what is happening.

2022-11-21 20:15 UTC, jedwards-habana commented on .github/workflows/snowflake_unittests.yaml
> +  build:
unittest step.

2022-11-21 20:15 UTC, jedwards-habana commented on .github/workflows/wiki_unittests.yaml
> +  build:
unittest step.

2022-11-30 19:29 UTC, madhuintel commented on .github/workflows/pr-snowflake-connector.yaml
> +      - pipeline-test
As discussed, I have updated all the files.

2022-12-05 15:43 UTC, jedwards-habana approved these changes
LGTM.

2022-12-05 16:03 UTC, merged